//utils/index.js
export {
  isValidCodePoint,
  toSafeDisplay,
  safeSubstring,
  getUtf8ByteLength,
  truncateByBytes,
  isValidUtf8,
  isValidIdentifier,
  toSafeNumber,
  getDisplayWidth,
  padToDisplayWidth,
  clamp,
  isWhitespaceOnly,
  normalizeWhitespace,
  smartSplit,
  removeDiacritics,
  titleCase,
  toCamelCase,
  toSnakeCase,
  toKebabCase,
  reverseString,
  countSubstring,
  insertAt,
  removeRange,
  hashCode,
  isPalindrome
} from './core.js';
export {
  countCodePoints,
  getCharFrequencies,
  isAscii,
  getStringMetrics,
  getWordCount,
  getSentenceCount,
  getParagraphCount,
  getLineCount,
  getReadabilityMetrics,
  estimateSyllableCount,
  getComplexityScore,
  analyzeCharacterDistribution,
  getEncodingComplexity,
  detectStringType,
  getAdvancedMetrics
} from './analysis.js';
export {
  detectEncoding,
  visualizeCodePoints,
  analyzeString,
  compareStrings,
  debugEntityDecode,
  formatDebugOutput,
  createDebugger,
  detectScripts,
  getCategoryBreakdown
} from './debug.js';
export {
  escapeForRegex,
  escapeForCssSelector,
  escapeForJson,
  encodeUriComponentSafe,
  decodeUriComponentSafe,
  escapeForHtml,
  escapeForXml,
  escapeForShell,
  escapeForSqlIdentifier,
  escapeForLdapFilter,
  escapeForCsv,
  escapeForLatex,
  escapeForMarkdown,
  escapeForJavaScript,
  escapeFor,
  batchEscape,
  escapeIfNeeded
} from './escape.js';
export {
  toSlug,
  toBase64,
  fromBase64,
  generateRandomUnicode,
  generateId,
  generatePassword,
  generateUuid,
  generateNanoId,
  generateHash,
  generatePlaceholder,
  generateTestData,
  generateRegexPattern
} from './generate.js';
export { 
  stripNonPrintable,
  hasUnsafeChars,
  isHtmlSafe,
  containsDirectionOverride,
  hasMixedScripts,
  sanitizeString,
  detectHomoglyphs,
  hasInvisibleChars,
  containsMaliciousPatterns,
  validateEmail,
  validateUrl,
  detectPhishingIndicators,
  securityScore,
  normalizeSecure
} from './security.js';
export {
  toCodePoints,
  fromCodePoints,
  splitGraphemes,
  normalizeUnicode,
  getGraphemeCount,
  getUnicodeCategory,
  getUnicodeBlock,
  getScript,
  hasMixedScripts,
  hasRtlText,
  getTextDirection,
  isEmoji,
  hasEmojis,
  countEmojis,
  analyzeUnicode,
  transformCase,
} from './unicode.js';
